# Generated by Django 5.2.15 on 2026-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_per_question_sec',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
