# Generated by Django 5.2.15 on 2026-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLimitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_files_per_day', models.PositiveIntegerField(default=3)),
                ('max_rows_per_file', models.PositiveIntegerField(default=5000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Import limiti sozlamalari',
                'verbose_name_plural': 'Import limiti sozlamalari',
                'db_table': 'import_limit_settings',
            },
        ),
    ]
